trigger:
  branches:
    include:
    - main

stages:
  - stage: cicd
    jobs: 
      - job:build_job
          pool: BuildPool
          steps:
            name: Build
              mvn clean install
          
          
        
  
  
